language: python
sudo: required
python:
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.5-dev" # 3.5 development branch
  - "3.6"
  - "3.6-dev" # 3.6 development branch
  - "nightly" # currently points to 3.7-dev

virtualenv:
  system_site_packages: true

os:
- osx
- linux

before_install: source scripts/split_repo_slug.sh

install: scripts/deps.sh

script: travis_wait scripts/install.sh

deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: "${SECURE_KEY}"
  file:
  - "src/dist/${REPO}_${TRAVIS_TAG}_${TRAVIS_OS_NAME}.zip"
  on:
    tags: true
    all_branches: true
    repo: ${TRAVIS_REPO_SLUG}
